import { Inter } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <CartProvider>
          <main className="flex-grow">
            <Navbar />
            <div>{children}</div>
            <Footer />
          </main>
        </CartProvider>
      </body>
    </html>
  );
}
